changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Build and Packaging
      labels:
        - build
        - release
    - title: Tests and CI
      labels:
        - tests
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
