      PROGRAM BLKDAT
      INTEGER LOW, HIGH
      COMMON /LIMITS/ LOW, HIGH
      WRITE (*, 100) LOW, HIGH
  100 FORMAT (I1, 1X, I1)
      END

      BLOCK DATA INITL
      INTEGER LOW, HIGH
      COMMON /LIMITS/ LOW, HIGH
      DATA LOW, HIGH /3, 9/
      END
