      PROGRAM CSHARE
      INTEGER LEFT, RIGHT
      COMMON /COUNTS/ LEFT, RIGHT
      LEFT = 10
      RIGHT = 20
      CALL BUMP
      WRITE (*, 100) LEFT, RIGHT
  100 FORMAT (I2, 1X, I2)
      END

      SUBROUTINE BUMP
      INTEGER FIRST, SECOND
      COMMON /COUNTS/ FIRST, SECOND
      FIRST = FIRST + 1
      SECOND = SECOND + 2
      RETURN
      END
