      PROGRAM CAS32
      COMPLEX VALUE, RESULT
      REAL RPART, IPART
      INTRINSIC REAL, AIMAG, CONJG
      VALUE = (2.0, -3.0)
      RESULT = CONJG(VALUE)
      RPART = REAL(RESULT)
      IPART = AIMAG(RESULT)
      WRITE (*,100) RPART, IPART
  100 FORMAT ('[',F5.1,',',F5.1,']')
      END
