      PROGRAM CAS33
      COMPLEX VALUE, RESULT
      REAL RPART, IPART
      INTRINSIC REAL, AIMAG, SQRT
      VALUE = (-3.0, 4.0)
      RESULT = SQRT(VALUE)
      RPART = REAL(RESULT)
      IPART = AIMAG(RESULT)
      WRITE (*,100) RPART, IPART
  100 FORMAT ('[',F5.1,',',F5.1,']')
      END
