      PROGRAM SAVLOC
      INTEGER RESET, FIRST, SECOND, THIRD
      RESET = 1
      CALL NEXT(RESET, FIRST)
      RESET = 0
      CALL NEXT(RESET, SECOND)
      CALL NEXT(RESET, THIRD)
      WRITE (*, 100) FIRST, SECOND, THIRD
  100 FORMAT (I1, 1X, I1, 1X, I1)
      END

      SUBROUTINE NEXT(RESET, VALUE)
      INTEGER RESET, VALUE, COUNTER
      SAVE COUNTER
      IF (RESET .EQ. 1) COUNTER = 0
      COUNTER = COUNTER + 1
      VALUE = COUNTER
      RETURN
      END
