      PROGRAM IFUNC
      INTEGER RESULT, TWICE
      RESULT = TWICE(7)
      WRITE (*, 100) RESULT
  100 FORMAT (I2)
      END

      INTEGER FUNCTION TWICE(VALUE)
      INTEGER VALUE
      TWICE = VALUE * 2
      RETURN
      END
